### ISSUE TITLE
Use background maps from Eurostat

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-ui#188]
Instead than default from OSM. Important to reflect the official position of EU on geopolitics.
Compatible with Leaflet.

**Comment by madewild** [comment]
To investigate...

**Comment by madewild** [comment]
Related to https://github.com/ec-doris/kohesio-data-import/issues/114

**Comment by raphdom** [comment]
Now, we are using the layers that is comming from the eurostat (https://europa.eu/webtools/maps/tiles/osmec2/)
Can you check if is stable and everything is okay?

**Comment by madewild** [comment]
Nice, I see this map is fully in English instead of multilingual, I guess it can be localised later in any EU language?

This is very important, @AThollard @gachpas @Bisiaam @slaven777 could you provide feedback before the merge?
also @D063520 @AlyHdr @DiaZork @svili could you test a bit?
https://dev.kohesio.eu/ is the new one (with eurostat maps), compare with https://kohesio.eu/ which is the previous one

**Comment by madewild** [comment]
(also note the © GISCO below the new map)

**Comment by madewild** [comment]
and @roberto-musmeci of course, oops ;)

**Comment by Bisiaam** [comment]
Regarding the map and language, I presented Kohesio to Country Team Bulgaria yesterday (on the dev site), but the regions and cities were in Cyrillic and I could not read them
But I prefer the map on dev, it's clearer we don't see all the capitals and the EEZ but the names of the countries

**Comment by madewild** [comment]
The main point is that's it's now the official EU map with official borders etc.
But it's also more easy to read, I agree. ;)

**Comment by gachpas** [comment]
+1 for the new one in dev..all in EN, clearer and sticking to the offcial borders
