### ISSUE TITLE
Disclaimer for using Projects near me 

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio-ui#247]
when using the near me feature, shouldn't have a message (or pop up with link to the About section) about location data that we collect?

**Comment by madewild** [comment]
not sure this is the best UX, but maybe a tooltip?

**Comment by madewild** [comment]
Add this in a general disclaimer with cookies, to approve at the beginning.

**Comment by madewild** [comment]
@AThollard what is your view on this?

**Comment by madewild** [comment]
It's already mentioned in the about
Do we need an additional pop-up to warn users if they don't look at the about page? Or good enough with the about?

**Comment by AThollard** [comment]
I think we need:
a) a pop-up warning users with a link to 
b) a dedicated section on data protection (e.g : https://webgate.ec.europa.eu/regiokm/display/ST/6.+Data+protection+for+RegioWiki)
@gachpas to include in our lists as a priority under the GDPR actions (also consult the DPC and finalise the record for GDPR to the DPO)

**Comment by madewild** [comment]
Dennis will remove this from the logs
I will update the about page to remove this part
So we don't need a popup
For the rest on data protection in general we can open another issue...

**Comment by madewild** [comment]
I changed the about page.
@D063520 can you confirm and close when we don't log the geolocation anymore?

**Comment by AThollard** [comment]
Fine you can close this one then
