### ISSUE TITLE
Filter beneficiaries by type (public/private)

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-ui#258]
Wait for https://github.com/ec-doris/kohesio-backend/issues/72 first

**Comment by madewild** [comment]
Implemented in the benef api: https://dev.kohesio.linkedopendata.eu/api/facet/eu/search/beneficiaries?offset=0&limit=15&country=https://linkedopendata.eu/entity/Q25&beneficiaryType=private

**Comment by raphdom** [comment]
Fixed on dev, can you check, please?

**Comment by madewild** [comment]
Very nice: https://dev.kohesio.eu/beneficiaries?beneficiaryType=Private
@roberto-musmeci @gachpas can you have a look? it's in the advanced filters (type)

**Comment by D063520** [comment]
I think one should put a disclaimer in the search indicating that we know the private/public thing only for a subset of the beneficiaries ....

**Comment by madewild** [comment]
Yes, and that it's based on machine learning... maybe a ? button next to the field like for the keyword search

**Comment by raphdom** [comment]
It is easy to add it, can you send me the text that I should include in the ? button, @madewild

**Comment by madewild** [comment]
"The type of beneficiary is guessed by an algorithm and is therefore not 100% accurate. Only a subset of beneficiaries is currently tagged with this information."

**Comment by madewild** [comment]
@roberto-musmeci feel free to suggest more precise wording to replace public/private

**Comment by roberto-musmeci** [comment]
> @roberto-musmeci feel free to suggest more precise wording to replace public/private

Just to be on the safe side, I would suggest
1) public and publicly-owned
2) private 
This allows us to consider private companies (e.g. ltd) owned by the state as public see https://dev.kohesio.eu/beneficiaries/Q276795

**Comment by madewild** [comment]
I discussed with Anne and we propose to leave just public/private for now for clarity's sake.
We can discuss improvements for next release...
